### ISSUE TITLE
Hover filtri Bazaar

### ISSUE THREAD

**Issue by v1proxy** [coompany/sos-tracker#10]
**Describe the bug**
I filtri del Bazaar funzionano come pulsanti ON/OFF ma l'hover non rispecchia questo funzionamento

**To Reproduce**
1. Vai in "Bazaar delle idee"
2. Clicca sui Filtri DIDATTICA/RICERCA/EVENTI
3. Vedi l'errore

**Expected behavior**
Essendo un filtro ON/OFF i Filtri dovrebbero essere in nero, poi una volta cliccati dovrebbero prendere il loro colore (oltre che in hover). Il colore rimane attivo finchè i filtri non vengono deselezionati.

**Screenshots**
![la_notte_della_taranta_-_bazaar_delle_idee_-_la_scuola_open_source_-_2018-05-08_17 01 18 - letizia guglielmi](https://user-images.githubusercontent.com/20812274/40278156-05c5775a-5c2c-11e8-948d-f1525b4b8f38.png)

**Desktop (please complete the following information):**
 - OS: ininfluente
 - Browser ininfluente
 - Version ininfluente

**Smartphone (please complete the following information):**
 - Device: ininfluente
 - OS: ininfluente
 - Browser ininfluente
 - Version ininfluente

**Additional context**

**Comment by acidghost** [comment]
Serve una descrizione più precisa del comportamento dei filtri colorati e quello per "tutti".

Nello specifico serve sapere comportamento ON, OFF ed HOVER con proprietà colore del testo e `font-weight` (bold, normale, etc.). In questo modo siamo sicuri di quello che vogliono.

**Comment by v1proxy** [comment]
NO INTERAZIONE: NERO
HOVER: COLORE COME ORA
CLICK=ON>COLORE COME ORA
CLICK=OFF>NERO COME INIZIO

**Comment by acidghost** [comment]
`font-weight`? e per "tutti"?

**Comment by v1proxy** [comment]
Non c'è cambiamento nel font weight rispetto all'attuale.
