### ISSUE TITLE
Attività non presenti in elenco

### ISSUE THREAD

**Issue by v1proxy** [coompany/sos-tracker#16]
**Describe the bug**
le attività in programma non escono nella pagina attività, sono visibili solo entrando nella categoria (quindi in attività non risulta mai nulla…)

**To Reproduce**
1. Vai in attività
2. Vedi l'errore

**Expected behavior**
Le attività dovrebbero vedersi fino alla loro data d'inizio

**Screenshots**
![screenshot 56](https://user-images.githubusercontent.com/20812274/41498224-49c992aa-7168-11e8-9767-d4492a6483be.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by acidghost** [comment]
Tutto funziona correttamente. Le attività sono visibili in "in programma" in base al campo "data di inizio". Se il campo è vuoto o la data è nel passato, l'attività compare solamente nelle 3 pagine filtrate (eventi, didattica e progetti) 
![screenshot-coompany-sos-ui-stage herokuapp com-2018 06 16-13-51-49](https://user-images.githubusercontent.com/1787979/41498387-78b224f2-716c-11e8-81b8-35b2733dfc40.png)
