### ISSUE TITLE
Aggiunta messaggio di benvenuto

### ISSUE THREAD

**Issue by v1proxy** [coompany/sos-tracker#21]
**Is your feature request related to a problem? Please describe.**
Aggiungere Messaggio di Benvenuto al primo accesso

**Describe the solution you'd like**
aggiungere nel messaggio in home post primo accesso "Arrr… benvenuto/a a bordo, dalla sezione membership puoi gestire il tuo account."

**Describe alternatives you've considered**

**Additional context**

**Comment by acidghost** [comment]
![whatsapp image 2018-10-16 at 14 50 18](https://user-images.githubusercontent.com/1787979/47021045-f277cf00-d15a-11e8-9ce4-2ed594684197.jpeg)
