### ISSUE TITLE
Caratteri FABLAB

### ISSUE THREAD

**Issue by v1proxy** [coompany/sos-tracker#3]
**Describe the bug**
i caratteri del box anteprima MACCHINARIO sono troppo grandi 

**To Reproduce**
1. Andare nella sezione Fablab
2. Scrolling fino alla sezione Macchinario

**Expected behavior**
Caratteri troppo grandi, ridurre da 1.5em a 1 em

**Screenshots**
![screenshot 9](https://user-images.githubusercontent.com/20812274/40270621-bfd04e46-5b90-11e8-837e-321b38055b4e.png)

**Desktop (please complete the following information):**
 - OS: ininfluente 
 - Browser: ininfluente
 - Version: ininfluente

**Smartphone (please complete the following information):**
 - Device: ininfluente
 - OS: ininfluente
 - Browser: ininfluente
 - Version: ininfluente

**Additional context**

**Comment by acidghost** [comment]
Già risolta
