### ISSUE TITLE
Inserimento "i miei preferiti" in menù

### ISSUE THREAD

**Issue by v1proxy** [coompany/sos-tracker#6]
**Is your feature request related to a problem? Please describe.**
"Non riesco a trovare facilmente i miei preferiti"

**Describe the solution you'd like**
Inserire "i miei preferiti" nel menù 

**Describe alternatives you've considered**

**Additional context**

**Comment by acidghost** [comment]
Questa è stata validata da SOS? In che posizione va inserita la voce?

**Comment by v1proxy** [comment]
Si è stata espressamente richiesta da SOS, va sotto "il mio profilo"
