### ISSUE TITLE
"UNISCITI AL TEAM" errata visualizzazione

### ISSUE THREAD

**Issue by v1proxy** [coompany/sos-tracker#7]
**Describe the bug**
Il testo "UNISCITI AL TEAM" nei progetti di ricerca è impaginato male

**To Reproduce**
1. Vai in Attività
2. Seleziona un qualsiasi progetto di ricerca
4. Scrolling della pagina fino a "UNISCITI AL TEAM"

**Expected behavior**
Il testo dovrebbe rimanere nei suoi limiti di layout

**Screenshots**
![screenshot 13](https://user-images.githubusercontent.com/20812274/40277988-252f57bc-5c29-11e8-8672-7e2fa889d43b.png)

**Desktop (please complete the following information):**
 - OS: tutti
 - Browser tutti
 - Version tutte

**Smartphone (please complete the following information):**

**Additional context**

**Comment by acidghost** [comment]
Di che dimensione va messo il testo "unisciti al team" (considerare lo spazio necessario alla lista skills richieste)?

Suggerisco di provare la dimensione nel browser (tramite es. Chrome Dev Tools) prima di confermarla qui.

**Comment by v1proxy** [comment]
0.5 rm in meno dell'attuale. In ogni caso va "giustificata" a destra in corrispondenza della linea nera

**Comment by acidghost** [comment]
1. rm non è un unità di misura, intendi `rem`?
2. mi serve la dimensione assoluta
3. giustificato vuol dire giustificato, ne a destra ne sinistra; cosa intendi?

**Comment by v1proxy** [comment]
si era un typo. 
Allineato a destra (esiste anche il giustificato allineato)
