### ISSUE TITLE
Eliminazione delle idee dopo l'approvazione

### ISSUE THREAD

**Issue by v1proxy** [coompany/sos-tracker#8]
**Is your feature request related to a problem? Please describe.**
Le idee approvate o scadute appaiono ancora nel bazaar dovrebbero sparire dalla classifica del Bazaar

**Describe the solution you'd like**
Le idee approvate o scadute dovrebbero sparire dalla classifica del Bazaar

**Describe alternatives you've considered**
1. Le idee scadute o approvate sono visibili solo su lato admin 
2. Le idee scadute o approvate sono visibili tramite filtro nel bazaar 

**Additional context**

**Comment by acidghost** [comment]
Quale delle due soluzioni è stata scelta da SOS?

**Comment by v1proxy** [comment]
Alla fine è stata scelta quella di renderle visibili solo da admin

**Comment by acidghost** [comment]
Quali sono i criteri perché le idee siano scadute? Per i progetti c'è il campo deadline, ma per imparare, insegnare ed eventi? Va usato il numero di giorni (deadline) della formula per lo score (al momento 90gg, configurabile in un file separato con gli altri parametri)?

**Comment by v1proxy** [comment]
Confermato il numero dei giorni della formula dello score
