### ISSUE TITLE
Non corrispondenza della voce "Github del progetto"

### ISSUE THREAD

**Issue by v1proxy** [coompany/sos-tracker#9]
**Describe the bug**
In fase di compilazione progetto viene chiesto il "Link al progetto" ma nel progetto viene mostrato come "github del progetto"

**To Reproduce**
1. Vai in Attività
2. Seleziona un progetto
3. Vedi l'errore

**Expected behavior**
Le due voci dovrebbero corrispondere (entrambe "Link al progetto")

**Screenshots**
![schermata 2018-05-07 alle 11 20 04 - la scuola open source xyz](https://user-images.githubusercontent.com/20812274/40278065-81d13534-5c2a-11e8-8013-4412cd58948f.png)

**Desktop (please complete the following information):**
 - OS: ininfluente
 - Browser ininfluente
 - Version ininfluente

**Smartphone (please complete the following information):**
 - Device: ininfluente
 - OS: ininfluente
 - Browser ininfluente
 - Version ininfluente

**Additional context**

**Comment by acidghost** [comment]
Bisogna cambiare la dicitura "Repository del progetto:" o "Github del progetto" nel lato user?

**Comment by v1proxy** [comment]
Link al progetto entrambi

**Comment by acidghost** [comment]
![screenshot-localhost-4200-2018 06 06-11-05-43](https://user-images.githubusercontent.com/1787979/41028404-a21f427a-6979-11e8-8c3f-d493206b9a14.png)

**Comment by v1proxy** [comment]
Sostituire "GITHUB DEL PROGETTO" con "LINK AL PROGETTO"
